name: "auto-merge"
on: [pull_request_target]

# No GITHUB_TOKEN permissions, as we use AUTOMERGE_TOKEN instead.
permissions: {}

jobs:
  auto-merge:
    uses: mdn/workflows/.github/workflows/auto-merge.yml@main
    with:
      target-repo: "mdn/release-dashboard"
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
